name = "zero-point-labs-dashboard"
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "zero-point-labs-dashboard"
database_id = "3ce53a6b-3fbd-4c2b-86a8-ff1ecf8e2237"

[env.production]
name = "zero-point-labs-dashboard"

[[env.production.d1_databases]]
binding = "DB"
database_name = "zero-point-labs-dashboard"
database_id = "3ce53a6b-3fbd-4c2b-86a8-ff1ecf8e2237"

[env.preview]
name = "zero-point-labs-dashboard-preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "zero-point-labs-dashboard"
database_id = "3ce53a6b-3fbd-4c2b-86a8-ff1ecf8e2237" 